#!/bin/bash

# Display the colour codes for use in $PS1 etc.
#  THESE ARE FOREGROUND COLOURS
echo -ne "\e[0;30m\\\[\\\e[0;30m\\\] "
echo -ne "\e[0;31m\\\[\\\e[0;31m\\\] "
echo -ne "\e[0;32m\\\[\\\e[0;32m\\\] "
echo -e "\e[0;33m\\\[\\\e[0;33m\\\] "
echo -ne "\e[0;34m\\\[\\\e[0;34m\\\] "
echo -ne "\e[0;35m\\\[\\\e[0;35m\\\] "
echo -ne "\e[0;36m\\\[\\\e[0;36m\\\] "
echo -e "\e[0;37m\\\[\\\e[0;37m\\\] "
echo -ne "\e[1;30m\\\[\\\e[1;30m\\\] "
echo -ne "\e[1;31m\\\[\\\e[1;31m\\\] "
echo -ne "\e[1;32m\\\[\\\e[1;32m\\\] "
echo -e "\e[1;33m\\\[\\\e[1;33m\\\] "
echo -ne "\e[1;34m\\\[\\\e[1;34m\\\] "
echo -ne "\e[1;35m\\\[\\\e[1;35m\\\] "
echo -ne "\e[1;36m\\\[\\\e[1;36m\\\] "
echo -e "\e[1;37m\\\[\\\e[1;37m\\\] "

# THESE ARE BACKGROUND COLOURS
echo -ne "\e[0;40m\\\[\\\e[0;40m\\\]\e[0;48m "
echo -ne "\e[0;41m\\\[\\\e[0;41m\\\]\e[0;48m "
echo -ne "\e[0;42m\\\[\\\e[0;42m\\\]\e[0;48m "
echo -e "\e[0;43m\\\[\\\e[0;43m\\\]\e[0;48m "
echo -ne "\e[0;44m\\\[\\\e[0;44m\\\]\e[0;48m "
echo -ne "\e[0;45m\\\[\\\e[0;45m\\\]\e[0;48m "
echo -ne "\e[0;46m\\\[\\\e[0;46m\\\]\e[0;48m "
echo -e "\e[0;47m\\\[\\\e[0;47m\\\]\e[0;48m "
echo -e "\e[0;48m\\\[\\\e[0;48m\\\]\e[0;48m "

