#!/bin/bash
#
# colours - A script to display the ANSI codes for use in BASH
# using their ANSI colour, for easy visual identification of the
# ANSI code for the colour you are looking for.
#
# Copyright (c) 2012 Mike Mallett <mike@nerdcore.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#  THESE ARE FOREGROUND COLOURS
echo -ne "\e[0;30m\\\[\\\e[0;30m\\\] "
echo -ne "\e[0;31m\\\[\\\e[0;31m\\\] "
echo -ne "\e[0;32m\\\[\\\e[0;32m\\\] "
echo -e "\e[0;33m\\\[\\\e[0;33m\\\] "
echo -ne "\e[0;34m\\\[\\\e[0;34m\\\] "
echo -ne "\e[0;35m\\\[\\\e[0;35m\\\] "
echo -ne "\e[0;36m\\\[\\\e[0;36m\\\] "
echo -e "\e[0;37m\\\[\\\e[0;37m\\\] "
echo -ne "\e[1;30m\\\[\\\e[1;30m\\\] "
echo -ne "\e[1;31m\\\[\\\e[1;31m\\\] "
echo -ne "\e[1;32m\\\[\\\e[1;32m\\\] "
echo -e "\e[1;33m\\\[\\\e[1;33m\\\] "
echo -ne "\e[1;34m\\\[\\\e[1;34m\\\] "
echo -ne "\e[1;35m\\\[\\\e[1;35m\\\] "
echo -ne "\e[1;36m\\\[\\\e[1;36m\\\] "
echo -e "\e[1;37m\\\[\\\e[1;37m\\\] "

# THESE ARE BACKGROUND COLOURS
echo -ne "\e[0;40m\\\[\\\e[0;40m\\\]\e[0;48m "
echo -ne "\e[0;41m\\\[\\\e[0;41m\\\]\e[0;48m "
echo -ne "\e[0;42m\\\[\\\e[0;42m\\\]\e[0;48m "
echo -e "\e[0;43m\\\[\\\e[0;43m\\\]\e[0;48m "
echo -ne "\e[0;44m\\\[\\\e[0;44m\\\]\e[0;48m "
echo -ne "\e[0;45m\\\[\\\e[0;45m\\\]\e[0;48m "
echo -ne "\e[0;46m\\\[\\\e[0;46m\\\]\e[0;48m "
echo -e "\e[0;47m\\\[\\\e[0;47m\\\]\e[0;48m "
echo -e "\e[0;48m\\\[\\\e[0;48m\\\]\e[0;48m "

